// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost/mattermost-plugin-api/experimental/common (interfaces: ChannelAPI)

// Package mock_api is a generated GoMock package.
package mock_api

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/mattermost/mattermost-server/v5/model"
	reflect "reflect"
)

// MockChannelAPI is a mock of ChannelAPI interface
type MockChannelAPI struct {
	ctrl     *gomock.Controller
	recorder *MockChannelAPIMockRecorder
}

// MockChannelAPIMockRecorder is the mock recorder for MockChannelAPI
type MockChannelAPIMockRecorder struct {
	mock *MockChannelAPI
}

// NewMockChannelAPI creates a new mock instance
func NewMockChannelAPI(ctrl *gomock.Controller) *MockChannelAPI {
	mock := &MockChannelAPI{ctrl: ctrl}
	mock.recorder = &MockChannelAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChannelAPI) EXPECT() *MockChannelAPIMockRecorder {
	return m.recorder
}

// GetDirect mocks base method
func (m *MockChannelAPI) GetDirect(arg0, arg1 string) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirect", arg0, arg1)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirect indicates an expected call of GetDirect
func (mr *MockChannelAPIMockRecorder) GetDirect(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirect", reflect.TypeOf((*MockChannelAPI)(nil).GetDirect), arg0, arg1)
}
